# Site settings
name: Keavnn'Blog
email: 271668153@qq.com
author: Keavnn
url: https://github.com/StepNeverStop/
resume_site: http://www.baidu.com/
github: https://github.com/StepNeverStop/
baseurl: ""
description: Actually, less is more!
meta_description: Keavnn
motto: If it is to be, it is up to me.
banner: Keep try, find the way to knowã€‚

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: StepNeverStop

# Build settings
markdown: kramdown

baidu_analysis: 94be4b0f9fc5d94cc0d0415ea6761ae9

